const DesayunosList = [
  {
    id: 1,
    titulo: '',
    description: 'Plato de fruta de temporada',
    price: 95,
    print1: '',
    print2: '',
  },
  {
    id: 2,
    description: 'Hot Cakes coco Jaguar Bañados con salsa de chocolate y coco rallado, acompañado con fruta y tocino',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 3,
    description: 'Pan tostado Frances acompañado con fruta y tocino',
    price: 115,
    print1: '',
    print2: '',
  },
  {
    id: 4,
    description: 'Wafles de la casa bañados con crema batida, chispas de chocolate y aderezo de fresa, acompañados con frutas de temporada',
    price: 105,
    print1: '',
    print2: '',
  },
  {
    id: 5,
    description: 'Wafles de canela, bañados de aderezo de chocolate, canela y fresas picadas, acompañado con manzanas cocinas con canela',
    price: 105,
    print1: '',
    print2: '',
  },
  {
    id: 6,
    description: 'Wafles Jaguar con jamón, queso y tocino.',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 7,
    description: 'Desayuno Jaguar: 2 huevos al gusto, fruta, tocino',
    price: 145,
    print1: '',
    print2: '',
  },
  {
    id: 8,
    description: 'Huevos benedictinos sobre bisquet y jamón, acompañados con papas al horno',
    price: 165,
    print1: '',
    print2: '',
  },
  {
    id: 9,
    description: 'Huevos divorciados con salsa verde y roja, acompañados con frijoles y queso panela',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 10,
    description: 'Huevos urbanos: huevos con frijol, cebolla, queso panela y crema',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 11,
    description: 'Huevos al gusto (estrellados o revueltos). Jamon, tocino, salchicha o chorizo o a la mexicana, acompañados con frijjoles y papa al horno',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 12,
    description: 'Omellet al gusto. Ingredientes: jamón, tocino, salchicha o chizo, champiñones, tomate o cebolla.',
    price: 135,
    print1: '',
    print2: '',
  },
  {
    id: 13,
    description: 'Burrito: jamon, huevo, tocino con frijoles acompañados con papa al horno y ensalada cesar o natural',
    price: 145,
    print1: '',
    print2: '',
  },
  {
    id: 14,
    description: 'Quesadillas de pollo con aderezo de blue chesse con ensalada y pico de gallo, crema y salsas',
    price: 125,
    print1: '',
    print2: '',
  },
  {
    id: 15,
    description: 'Chilaquiles rojos o verdes con pollo y huevo con crema y queso panela',
    price: 135,
    print1: '',
    print2: '',
  },
  {
    id: 16,
    description: 'Enchiladas Rojas o verdes de pollo, con crema, queso panela, frijoles y ensalada',
    price: 145,
    print1: '',
    print2: '',
  },
  {
    id: 17,
    description: 'Enchiladas tricolor de pollo con crema, queso y panela, frijoles y ensalada',
    price: 145,
    print1: '',
    print2: '',
  },
  {
    id: 18,
    description: 'Enchiladas de mole con pollo, crema, cebolla y queso panela',
    price: 135,
    print1: '',
    print2: '',
  },
  {
    id: 19,
    description: 'Sandwich club de pollo con jamón, tocino, pollo, huevo, queso, ensalada, acompañado con papas fritas',
    price: 165,
    print1: '',
    print2: '',
  },
  {
    id: 20,
    description: 'Sandwich club Arrachera, jamón, queso, chorizo, arrachera y huevo con ensalada, acompañado con papas fritas',
    price: 185,
    print1: '',
    print2: '',
  },
];

export default DesayunosList;
